USE GuildCars
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Special')
DROP TABLE Special
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Sales')
DROP TABLE Sales
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'States')
DROP TABLE States
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Vehicle')
DROP TABLE Vehicle
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'PurchaseType')
DROP TABLE PurchaseType
GO


IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Contact')
DROP TABLE Contact
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Model')
DROP TABLE Model
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Make')
DROP TABLE Make
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'BodyStyle')
DROP TABLE BodyStyle
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name = 'Color')
DROP TABLE Color
GO


CREATE TABLE Color (
ColorId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ColorName VARCHAR(25) NOT NULL
)


CREATE TABLE BodyStyle (
BodyStyleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
BodyStyleName VARCHAR(10) 
)

CREATE TABLE Make (
MakeId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
MakeName NVARCHAR(30) NOT NULL,
UserId NVARCHAR(128) FOREIGN KEY REFERENCES AspNetUsers(Id) NOT NULL,
DateAdded DateTime2 NOT NULL default (getdate())
)

CREATE TABLE Model (
ModelId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ModelName NVARCHAR(30) NOT NULL,
MakeId INT FOREIGN KEY REFERENCES Make(MakeId) NOT NULL, 
UserId NVARCHAR(128) FOREIGN KEY REFERENCES AspNetUsers(Id) NOT NULL,
DateAdded DateTime2 NOT NULL default FORMAT(getdate(), 'yyyy-MM-dd')
)

CREATE TABLE Vehicle (
VehicleId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
MakeId INT FOREIGN KEY REFERENCES Make(MakeId) NOT NULL, 
ModelId INT FOREIGN KEY REFERENCES Model(ModelId) NOT NULL,
[Year] INT NOT NULL, 
BodyStyleId INT FOREIGN KEY REFERENCES BodyStyle(BodyStyleId) NOT NULL,
IsManualTransmission BIT NOT NULL, 
ExteriorColorId INT FOREIGN KEY REFERENCES Color(ColorId) NOT NULL,
InteriorColorId INT FOREIGN KEY REFERENCES Color(ColorId) NOT NULL,
UserId NVARCHAR(128) NOT NULL,
Mileage INT NOT NULL,
SalePrice MONEY NOT NULL,
MSRP MONEY NOT NULL,
Vin VARCHAR(17) UNIQUE NOT NULL,
[Description] NVARCHAR(1500) NOT NULL,
PhotoFile VARCHAR(255),
IsFeatured BIT NOT NULL,
IsNew BIT NOT NULL,
IsSold BIT NOT NULL,
DateAdded DateTime2 NOT NULL default (getdate())
)

CREATE TABLE Contact (
ContactId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] VARCHAR(35) NOT NULL,
Email VARCHAR(30) NULL,
Phone VARCHAR(13) NULL,
[Message] VARCHAR(500) NOT NULL,
)

CREATE TABLE PurchaseType (
PurchaseTypeId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PurchaseTypeName VARCHAR(15)
)

CREATE TABLE States (
StateId CHAR(2) PRIMARY KEY NOT NULL,
StateName VARCHAR(15) NOT NULL
)

CREATE TABLE Sales (
SalesId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
UserId NVARCHAR(128) NOT NULL,
[Name] VARCHAR(50) NOT NULL,
Phone VARCHAR(15),
Email VARCHAR(30),
Street1 VARCHAR(30) NOT NULL,
Street2 VARCHAR(30),
City VARCHAR(30) NOT NULL,
StateId CHAR(2) FOREIGN KEY REFERENCES States(StateId) NOT NULL,
Zipcode INT NOT NULL,
PurchaseTypeId INT FOREIGN KEY REFERENCES PurchaseType(PurchaseTypeId) NOT NULL,
VehicleId INT FOREIGN KEY REFERENCES Vehicle(VehicleId) NOT NULL,
PurchasePrice MONEY NOT NULL,
DateAdded DATETIME2 NOT NULL DEFAULT (getdate())
)



CREATE TABLE Special (
SpecialId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Title VARCHAR(50) NOT NULL,
[Description] VARCHAR(750)
)