//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdLibrary_Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dvd
    {
        public int DvdId { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public int ReleaseYearId { get; set; }
        public int DirectorId { get; set; }
        public int RatingId { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual ReleaseYear ReleaseYear { get; set; }

        public static explicit operator Dvd(ReleaseYear v)
        {
            throw new NotImplementedException();
        }
    }
}
